import {
  FastagStatus,
  InstallmentStatus,
  MaintenanceStatus,
  NotificationPriority,
  NotificationType,
  OPERATOR_MANAGEMENT_ROLES,
  formatCurrency,
  resolveDocumentValidity,
  resolveFastagHealth,
} from '@saarthi/shared';
import { prisma } from '../../database/prisma';
import { config } from '../../config/env';
import { logger } from '../../lib/logger';
import { cache } from '../../infra/cache';
import { withLock } from '../../infra/lock';
import { notifyOrganization } from '../notifications/notification.service';
import type { AuthContext } from '../../auth/context';

/**
 * The daily fleet brief.
 *
 * Deliberately *not* generated by a language model. A brief is read in ten
 * seconds before a working day starts, it is the same shape every morning, and
 * every line of it is a count — which is exactly the kind of output a model
 * adds risk to and nothing else. The rules below produce it; the copilot is
 * available to explain any line of it on request.
 *
 * The ordering is the product decision: what is already costing money, then
 * what will cost money this week, then what is merely worth knowing. An owner
 * who reads only the first two lines should have seen the important things.
 */

const briefLogger = logger.child({ module: 'ai:brief' });

export interface BriefItem {
  /** Machine-readable, so the UI can route a tap to the right screen. */
  kind:
    | 'SERVICE_OVERDUE'
    | 'SERVICE_DUE'
    | 'EMI_OVERDUE'
    | 'EMI_DUE'
    | 'DOCUMENT_EXPIRED'
    | 'DOCUMENT_EXPIRING'
    | 'DEVICE_OFFLINE'
    | 'FASTAG_LOW'
    | 'FASTAG_BLOCKED'
    | 'INCIDENT_OPEN'
    | 'TELEMETRY_ALERT'
    | 'CAPACITY';
  severity: 'CRITICAL' | 'HIGH' | 'NORMAL';
  count: number;
  headline: string;
  detail: string;
  actionUrl: string;
}

export interface DailyBrief {
  organizationId: string;
  generatedAt: string;
  /** Vehicles the fleet is actually running today. */
  activeVehicles: number;
  activeTrips: number;
  items: BriefItem[];
  /** The three things most worth doing first, in order. */
  priorities: { label: string; reason: string; actionUrl: string }[];
  /** True when nothing needs attention — worth saying explicitly. */
  allClear: boolean;
  basis: 'calculated';
}

const SEVERITY_ORDER: Record<BriefItem['severity'], number> = {
  CRITICAL: 0,
  HIGH: 1,
  NORMAL: 2,
};

function briefCacheKey(organizationId: string): string {
  return `saarthi:${config.env}:fleet:${organizationId}:daily-brief`;
}

/**
 * Build the brief for one organization.
 *
 * Every figure is a count from a query — nothing here is estimated, and nothing
 * is generated. Cached for a few minutes because a dashboard card and a
 * notification job will both ask for it within the same minute.
 */
export async function buildDailyBrief(organizationId: string): Promise<DailyBrief> {
  const cached = await cache.get<DailyBrief>(briefCacheKey(organizationId));
  if (cached) return cached;

  const now = new Date();
  const inSevenDays = new Date(now.getTime() + 7 * 86_400_000);

  const [
    activeVehicles,
    activeTrips,
    overdueService,
    dueService,
    overdueEmis,
    upcomingEmis,
    documents,
    offlineDevices,
    openIncidents,
    openAlerts,
    fastags,
  ] = await Promise.all([
    prisma.truck.count({ where: { organizationId, archivedAt: null } }),
    prisma.trip.count({
      where: { organizationId, status: { in: ['STARTED', 'IN_TRANSIT'] } },
    }),
    prisma.maintenanceRecord.count({
      where: { organizationId, status: MaintenanceStatus.SCHEDULED, scheduledAt: { lt: now } },
    }),
    prisma.maintenanceRecord.count({
      where: {
        organizationId,
        status: MaintenanceStatus.SCHEDULED,
        scheduledAt: { gte: now, lte: inSevenDays },
      },
    }),
    prisma.loanInstallment.findMany({
      where: {
        organizationId,
        status: InstallmentStatus.OVERDUE,
        loan: { status: { in: ['ACTIVE', 'DEFAULTED'] } },
      },
      select: { totalDue: true, amountPaid: true },
      take: 200,
    }),
    prisma.loanInstallment.findMany({
      where: {
        organizationId,
        dueDate: { gte: now, lte: inSevenDays },
        status: {
          in: [
            InstallmentStatus.UPCOMING,
            InstallmentStatus.DUE_SOON,
            InstallmentStatus.DUE_TODAY,
            InstallmentStatus.PARTIALLY_PAID,
          ],
        },
        loan: { status: { in: ['ACTIVE', 'DEFAULTED'] } },
      },
      select: { totalDue: true, amountPaid: true },
      take: 200,
    }),
    prisma.document.findMany({
      where: {
        organizationId,
        deletedAt: null,
        expiryDate: { not: null, lte: inSevenDays },
      },
      select: { expiryDate: true, verificationStatus: true },
      take: 500,
    }),
    prisma.hardwareDevice.count({
      where: { organizationId, status: 'OFFLINE', archivedAt: null },
    }),
    prisma.sosIncident.count({
      where: {
        organizationId,
        status: {
          in: ['TRIGGERED', 'BROADCASTING', 'ACKNOWLEDGED', 'HELP_ASSIGNED', 'ASSISTANCE_ARRIVED'],
        },
      },
    }),
    prisma.telemetryAlert.count({
      where: {
        organizationId,
        status: 'OPEN',
        occurredAt: { gte: new Date(now.getTime() - 86_400_000) },
      },
    }),
    prisma.fastagAccount.findMany({
      where: { organizationId, closedAt: null },
      select: {
        status: true,
        balance: true,
        balanceUpdatedAt: true,
        lowBalanceThreshold: true,
        expiresAt: true,
      },
      take: 500,
    }),
  ]);

  /*
   * FASTag health.
   *
   * Evaluated through the same rule the tag screen uses, so the brief cannot
   * disagree with the page it links to. Tags with no recorded balance are not
   * counted as low — "we do not know" is not a warning.
   */
  let lowTags = 0;
  let blockedTags = 0;
  for (const tag of fastags) {
    const health = resolveFastagHealth({
      status: tag.status as FastagStatus,
      balance: tag.balance === null ? null : Number(tag.balance),
      balanceUpdatedAt: tag.balanceUpdatedAt,
      lowBalanceThreshold:
        tag.lowBalanceThreshold === null ? null : Number(tag.lowBalanceThreshold),
      expiresAt: tag.expiresAt,
    });
    if (health.health === 'BLOCKED') blockedTags += 1;
    else if (health.health === 'LOW_BALANCE') lowTags += 1;
  }

  const outstanding = (rows: { totalDue: unknown; amountPaid: unknown }[]): number =>
    Number(
      rows
        .reduce((sum, row) => sum + (Number(row.totalDue) - Number(row.amountPaid)), 0)
        .toFixed(2),
    );

  let expired = 0;
  let expiring = 0;
  for (const document of documents) {
    const { validity } = resolveDocumentValidity({
      expiryDate: document.expiryDate,
      verificationStatus: document.verificationStatus,
    });
    if (validity === 'EXPIRED') expired += 1;
    else if (validity === 'EXPIRING_SOON') expiring += 1;
  }

  const items: BriefItem[] = [];

  if (openIncidents > 0) {
    items.push({
      kind: 'INCIDENT_OPEN',
      severity: 'CRITICAL',
      count: openIncidents,
      headline: `${openIncidents} open incident${openIncidents === 1 ? '' : 's'}`,
      detail: 'Someone is waiting on a response.',
      actionUrl: '/sos',
    });
  }

  if (overdueEmis.length > 0) {
    items.push({
      kind: 'EMI_OVERDUE',
      severity: 'CRITICAL',
      count: overdueEmis.length,
      headline: `${overdueEmis.length} EMI${overdueEmis.length === 1 ? '' : 's'} overdue`,
      detail: `${formatCurrency(outstanding(overdueEmis))} past its due date.`,
      actionUrl: '/fleet/loans',
    });
  }

  if (blockedTags > 0) {
    items.push({
      kind: 'FASTAG_BLOCKED',
      severity: 'CRITICAL',
      count: blockedTags,
      headline: `${blockedTags} FASTag${blockedTags === 1 ? '' : 's'} blocked`,
      detail: 'Toll will be charged at double the cash rate until the issuer clears it.',
      actionUrl: '/fleet/toll',
    });
  }

  if (expired > 0) {
    items.push({
      kind: 'DOCUMENT_EXPIRED',
      severity: 'CRITICAL',
      count: expired,
      headline: `${expired} document${expired === 1 ? '' : 's'} expired`,
      detail: 'A vehicle on the road with a lapsed document is a fine waiting to happen.',
      actionUrl: '/fleet/documents?filter=expired',
    });
  }

  if (overdueService > 0) {
    items.push({
      kind: 'SERVICE_OVERDUE',
      severity: 'HIGH',
      count: overdueService,
      headline: `${overdueService} service job${overdueService === 1 ? '' : 's'} overdue`,
      detail: 'Booked but past the scheduled date.',
      actionUrl: '/fleet/maintenance',
    });
  }

  if (upcomingEmis.length > 0) {
    items.push({
      kind: 'EMI_DUE',
      severity: 'HIGH',
      count: upcomingEmis.length,
      headline: `${upcomingEmis.length} EMI${upcomingEmis.length === 1 ? '' : 's'} due this week`,
      detail: `${formatCurrency(outstanding(upcomingEmis))} falls due in the next seven days.`,
      actionUrl: '/fleet/loans',
    });
  }

  if (expiring > 0) {
    items.push({
      kind: 'DOCUMENT_EXPIRING',
      severity: 'HIGH',
      count: expiring,
      headline: `${expiring} document${expiring === 1 ? '' : 's'} expiring`,
      detail: 'Renew before the vehicle is stopped.',
      actionUrl: '/fleet/documents?filter=expiring',
    });
  }

  if (lowTags > 0) {
    items.push({
      kind: 'FASTAG_LOW',
      severity: 'HIGH',
      count: lowTags,
      headline: `${lowTags} FASTag${lowTags === 1 ? '' : 's'} low on balance`,
      detail: 'Roughly one more national plaza each before a truck is stopped at a barrier.',
      actionUrl: '/fleet/toll',
    });
  }

  if (offlineDevices > 0) {
    items.push({
      kind: 'DEVICE_OFFLINE',
      severity: 'NORMAL',
      count: offlineDevices,
      headline: `${offlineDevices} device${offlineDevices === 1 ? '' : 's'} offline`,
      detail: 'A silent device looks the same as a parked truck on the map.',
      actionUrl: '/devices',
    });
  }

  if (dueService > 0) {
    items.push({
      kind: 'SERVICE_DUE',
      severity: 'NORMAL',
      count: dueService,
      headline: `${dueService} service job${dueService === 1 ? '' : 's'} due this week`,
      detail: 'Scheduled within the next seven days.',
      actionUrl: '/fleet/maintenance',
    });
  }

  if (openAlerts > 0) {
    items.push({
      kind: 'TELEMETRY_ALERT',
      severity: 'NORMAL',
      count: openAlerts,
      headline: `${openAlerts} telemetry alert${openAlerts === 1 ? '' : 's'} in the last day`,
      detail: 'Rule-based detections from connected hardware.',
      actionUrl: '/telemetry/alerts',
    });
  }

  items.sort((a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity]);

  const brief: DailyBrief = {
    organizationId,
    generatedAt: now.toISOString(),
    activeVehicles,
    activeTrips,
    items,
    priorities: items.slice(0, 3).map((item) => ({
      label: item.headline,
      reason: item.detail,
      actionUrl: item.actionUrl,
    })),
    allClear: items.length === 0,
    basis: 'calculated',
  };

  // Short window: the brief is read repeatedly through the morning, and a fleet
  // that has just cleared an item should see it disappear.
  await cache.set(briefCacheKey(organizationId), brief, 300);
  return brief;
}

/** The caller's own brief. Tenant scoping comes from the session, not input. */
export async function dailyBriefFor(
  _auth: AuthContext,
  organizationId: string,
): Promise<DailyBrief> {
  return buildDailyBrief(organizationId);
}

/**
 * Send the brief to every fleet that has something worth reading.
 *
 * Organizations with nothing outstanding are skipped entirely. A daily "all
 * clear" notification is how a fleet learns to swipe the morning brief away
 * without reading it, and then misses the one that mattered.
 */
export async function runDailyBriefSweep(): Promise<{ sent: number; skipped: number }> {
  const outcome = await withLock('jobs:ai:daily-brief', 10 * 60_000, async () => {
    const organizations = await prisma.organization.findMany({
      where: { type: { in: ['FLEET_OWNER', 'MOBILITY_PROVIDER'] } },
      select: { id: true },
      take: 1000,
    });

    let sent = 0;
    let skipped = 0;

    for (const organization of organizations) {
      const brief = await buildDailyBrief(organization.id);

      if (brief.allClear || brief.items.length === 0) {
        skipped += 1;
        continue;
      }

      const critical = brief.items.filter((item) => item.severity === 'CRITICAL').length;

      await notifyOrganization(organization.id, {
        type: NotificationType.SYSTEM,
        title: `Today: ${brief.priorities[0]?.label ?? 'fleet brief'}`,
        body: brief.items
          .slice(0, 4)
          .map((item) => item.headline)
          .join(' · '),
        priority: critical > 0 ? NotificationPriority.HIGH : NotificationPriority.NORMAL,
        actionUrl: '/dashboard',
        roles: OPERATOR_MANAGEMENT_ROLES,
      });
      sent += 1;
    }

    briefLogger.info({ sent, skipped }, 'Daily fleet brief sweep complete');
    return { sent, skipped };
  });

  return outcome ?? { sent: 0, skipped: 0 };
}
