import * as React from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import {
  AlertTriangle,
  ArrowRight,
  Banknote,
  CircleCheck,
  Clock,
  FileWarning,
  Radio,
  Siren,
  Wrench,
} from 'lucide-react';
import { Permission } from '@saarthi/shared';
import { api } from '@/lib/api-client';
import type { DailyBrief, BriefItem } from '@/lib/api-types';
import { useAuth } from '@/features/auth/auth-context';
import { SectionHeader } from '@/components/common/page-header';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { cn } from '@/lib/utils';

/**
 * The morning brief.
 *
 * A card on the dashboard rather than a screen of its own, because it is read
 * in the ten seconds before a working day starts and then not returned to. Its
 * ordering is the whole product: what is already costing money or safety, then
 * what will this week, then what is merely worth knowing.
 *
 * Nothing here is generated by a model. Every line is a count from a query, and
 * the card says so — an operator acting on "3 EMIs overdue" deserves to know it
 * is a fact rather than a summary someone's language model produced.
 */

const ICONS: Record<BriefItem['kind'], React.ComponentType<{ className?: string }>> = {
  SERVICE_OVERDUE: Wrench,
  SERVICE_DUE: Wrench,
  EMI_OVERDUE: Banknote,
  EMI_DUE: Banknote,
  DOCUMENT_EXPIRED: FileWarning,
  DOCUMENT_EXPIRING: FileWarning,
  DEVICE_OFFLINE: Radio,
  INCIDENT_OPEN: Siren,
  TELEMETRY_ALERT: AlertTriangle,
  CAPACITY: Clock,
};

const SEVERITY_STYLES: Record<
  BriefItem['severity'],
  { badge: 'destructive' | 'warning' | 'muted'; accent: string }
> = {
  CRITICAL: { badge: 'destructive', accent: 'text-destructive' },
  HIGH: { badge: 'warning', accent: 'text-warning' },
  NORMAL: { badge: 'muted', accent: 'text-muted-foreground' },
};

export function DailyBriefCard(): React.ReactElement | null {
  const { can } = useAuth();

  const brief = useQuery({
    queryKey: ['daily-brief'],
    queryFn: () => api.get<DailyBrief>('/ai/daily-brief'),
    enabled: can(Permission.ANALYTICS_READ),
    // Regenerated server-side every few minutes; refetching harder would just
    // return the same cached brief.
    staleTime: 5 * 60_000,
  });

  if (!can(Permission.ANALYTICS_READ)) return null;

  if (brief.isLoading) {
    return (
      <Card>
        <CardContent className="space-y-3 pt-6">
          <Skeleton className="h-4 w-40" />
          <Skeleton className="h-3 w-full" />
          <Skeleton className="h-3 w-4/5" />
        </CardContent>
      </Card>
    );
  }

  // A failed brief is not worth an error state on a dashboard that has plenty
  // else to show. It simply does not appear.
  if (brief.isError || !brief.data) return null;

  const data = brief.data;

  return (
    <Card className={data.items[0]?.severity === 'CRITICAL' ? 'border-destructive/40' : undefined}>
      <CardHeader className="pb-3">
        <SectionHeader
          title="Today"
          description={`${data.activeVehicles} vehicle${data.activeVehicles === 1 ? '' : 's'} · ${data.activeTrips} trip${data.activeTrips === 1 ? '' : 's'} running`}
        />
      </CardHeader>

      <CardContent className="space-y-2 pt-0">
        {data.allClear ? (
          <div className="flex items-start gap-2 rounded-lg border border-success/30 bg-success/5 p-3">
            <CircleCheck className="mt-0.5 h-4 w-4 shrink-0 text-success" />
            <div>
              <p className="text-sm font-medium">Nothing needs attention</p>
              <p className="text-xs text-muted-foreground">
                No overdue service, no lapsed documents, no EMI past its date and no open
                incidents.
              </p>
            </div>
          </div>
        ) : (
          data.items.map((item) => {
            const Icon = ICONS[item.kind] ?? AlertTriangle;
            const style = SEVERITY_STYLES[item.severity];

            return (
              <Link
                key={item.kind}
                to={item.actionUrl}
                className="flex items-start justify-between gap-3 rounded-lg border border-border p-3 transition-colors hover:bg-muted/50"
              >
                <div className="flex min-w-0 items-start gap-2.5">
                  <Icon className={cn('mt-0.5 h-4 w-4 shrink-0', style.accent)} />
                  <div className="min-w-0">
                    <p className="flex flex-wrap items-center gap-2 text-sm font-medium">
                      {item.headline}
                      {item.severity === 'CRITICAL' ? (
                        <Badge variant={style.badge} size="sm">
                          Now
                        </Badge>
                      ) : null}
                    </p>
                    <p className="mt-0.5 text-xs text-muted-foreground">{item.detail}</p>
                  </div>
                </div>
                <ArrowRight className="mt-0.5 h-3.5 w-3.5 shrink-0 text-muted-foreground" />
              </Link>
            );
          })
        )}

        <p className="pt-1 text-2xs text-muted-foreground">
          Counted from your own records. Nothing on this card is estimated or generated.
        </p>
      </CardContent>
    </Card>
  );
}
