import crypto from 'node:crypto';

/**
 * Generates small but genuinely valid PDF files for the demo document set, so
 * upload, download, preview and checksum flows all work against real bytes
 * rather than placeholder text.
 */
export function buildDemoPdf(title: string, lines: string[]): Buffer {
  const escape = (value: string): string =>
    value.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');

  const content = [
    'BT',
    '/F1 18 Tf',
    '58 760 Td',
    `(${escape(title)}) Tj`,
    '/F1 11 Tf',
    '0 -30 Td',
    ...lines.flatMap((line) => [`(${escape(line)}) Tj`, '0 -18 Td']),
    '0 -14 Td',
    '(This is a Saarthi demo document generated by the local seed.) Tj',
    'ET',
  ].join('\n');

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
    `<< /Length ${Buffer.byteLength(content, 'latin1')} >>\nstream\n${content}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ];

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];

  objects.forEach((body, index) => {
    offsets.push(Buffer.byteLength(pdf, 'latin1'));
    pdf += `${index + 1} 0 obj\n${body}\nendobj\n`;
  });

  const xrefOffset = Buffer.byteLength(pdf, 'latin1');
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets) {
    pdf += `${offset.toString().padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;

  return Buffer.from(pdf, 'latin1');
}

export function checksumOf(buffer: Buffer): string {
  return crypto.createHash('sha256').update(buffer).digest('hex');
}
