import { z } from 'zod';
import {
  csvEnum,
  dateRangeSchema,
  optionalTrimmedString,
  paginationSchema,
  trimmedString,
  uuidSchema,
} from './common';

/**
 * Vehicle finance input contracts.
 *
 * Loan terms are validated hard because every downstream number — the EMI, the
 * schedule, the outstanding balance — is derived from them. A rate typed as
 * `1050` instead of `10.50` would otherwise produce a schedule that looks
 * authoritative and is nonsense.
 */

const LOAN_TYPES = [
  'TERM_LOAN',
  'HYPOTHECATION',
  'LEASE',
  'HIRE_PURCHASE',
  'REFINANCE',
  'TOP_UP',
  'WORKING_CAPITAL',
  'OTHER',
] as const;

const INTEREST_TYPES = ['FLAT', 'REDUCING_BALANCE', 'FLOATING'] as const;
const EMI_FREQUENCIES = ['MONTHLY', 'QUARTERLY', 'HALF_YEARLY', 'ANNUAL'] as const;
const LOAN_STATUSES = [
  'DRAFT',
  'ACTIVE',
  'ON_HOLD',
  'CLOSED',
  'FORECLOSED',
  'DEFAULTED',
  'CANCELLED',
] as const;
const INSTALLMENT_STATUSES = [
  'UPCOMING',
  'DUE_SOON',
  'DUE_TODAY',
  'PAID',
  'OVERDUE',
  'PARTIALLY_PAID',
  'WAIVED',
  'UNKNOWN',
] as const;
const PAYMENT_METHODS = [
  'AUTO_DEBIT',
  'NACH',
  'UPI',
  'BANK_TRANSFER',
  'CHEQUE',
  'CASH',
  'CARD',
  'OTHER',
] as const;
const PAYMENT_KINDS = [
  'INSTALLMENT',
  'PART_PREPAYMENT',
  'FORECLOSURE',
  'PENALTY',
  'CHARGES',
] as const;

export const loanTypeSchema = z.enum(LOAN_TYPES);
export const interestTypeSchema = z.enum(INTEREST_TYPES);
export const emiFrequencySchema = z.enum(EMI_FREQUENCIES);
export const loanStatusSchema = z.enum(LOAN_STATUSES);
export const installmentStatusSchema = z.enum(INSTALLMENT_STATUSES);
export const loanPaymentMethodSchema = z.enum(PAYMENT_METHODS);
export const loanPaymentKindSchema = z.enum(PAYMENT_KINDS);

/** A lender's own reference for the facility. Never generated by Saarthi. */
const loanNumberSchema = z
  .string()
  .transform((value) => value.trim().toUpperCase())
  .pipe(
    z
      .string()
      .min(3, 'Enter the loan account number from your agreement.')
      .max(64)
      .regex(/^[A-Z0-9][A-Z0-9\-/ ]*$/, 'A loan number may contain letters, digits, - and /.'),
  );

const amountSchema = (label: string) =>
  z.coerce
    .number()
    .positive(`Enter the ${label}.`)
    .max(1_000_000_000, 'Amount is unrealistically large.');

const optionalAmountSchema = z.coerce.number().min(0).max(1_000_000_000).optional();

/**
 * Reminder offsets in days relative to the due date.
 *
 * Negative is before, positive is after; the spec default is [-4, -1, +1]. The
 * range is bounded so a mistyped value cannot schedule a reminder a year out.
 */
export const reminderOffsetsSchema = z
  .array(z.coerce.number().int().min(-60).max(30))
  .max(3, 'At most three reminders can be configured.')
  .optional();

export const createLoanSchema = z
  .object({
    vehicleId: uuidSchema,
    loanNumber: loanNumberSchema,
    lenderName: trimmedString(2, 160),
    lenderBranch: optionalTrimmedString(160),
    borrowerName: optionalTrimmedString(160),
    loanType: loanTypeSchema.default('TERM_LOAN'),

    principal: amountSchema('loan amount'),
    disbursedAmount: optionalAmountSchema,
    annualRatePercent: z.coerce
      .number()
      .min(0, 'Interest rate cannot be negative.')
      .max(60, 'Enter the annual rate — 60% p.a. is the accepted ceiling.'),
    interestType: interestTypeSchema.default('REDUCING_BALANCE'),

    tenureMonths: z.coerce
      .number()
      .int()
      .min(1, 'Enter the tenure in months.')
      .max(360, 'Tenure cannot exceed 30 years.'),
    frequency: emiFrequencySchema.default('MONTHLY'),
    startDate: z.coerce.date(),
    firstDueDate: z.coerce.date().optional(),

    /** Supplied when the lender's EMI differs from Saarthi's computation. */
    emiAmount: optionalAmountSchema,

    autoDebitDay: z.coerce.number().int().min(1).max(31).optional(),
    mandateReference: optionalTrimmedString(64),
    accountNumber: optionalTrimmedString(34),

    reminderOffsets: reminderOffsetsSchema,
    notes: optionalTrimmedString(2000),
    /** Generate the amortisation schedule immediately. */
    generateSchedule: z.coerce.boolean().default(true),
    status: loanStatusSchema.default('ACTIVE'),
  })
  .refine(
    (value) => !value.disbursedAmount || value.disbursedAmount <= value.principal,
    {
      message: 'The disbursed amount cannot exceed the sanctioned principal.',
      path: ['disbursedAmount'],
    },
  )
  .refine(
    (value) => !value.firstDueDate || value.firstDueDate >= value.startDate,
    {
      message: 'The first installment cannot fall before the loan starts.',
      path: ['firstDueDate'],
    },
  );
export type CreateLoanInput = z.infer<typeof createLoanSchema>;

/**
 * Editable loan fields.
 *
 * Terms that the schedule is derived from are editable, but the service
 * regenerates only the *unpaid* tail when they change — rewriting settled
 * installments would falsify a payment history.
 */
export const updateLoanSchema = z.object({
  lenderName: trimmedString(2, 160).optional(),
  lenderBranch: optionalTrimmedString(160),
  borrowerName: optionalTrimmedString(160),
  loanType: loanTypeSchema.optional(),
  status: loanStatusSchema.optional(),
  annualRatePercent: z.coerce.number().min(0).max(60).optional(),
  interestType: interestTypeSchema.optional(),
  tenureMonths: z.coerce.number().int().min(1).max(360).optional(),
  frequency: emiFrequencySchema.optional(),
  emiAmount: optionalAmountSchema,
  autoDebitDay: z.coerce.number().int().min(1).max(31).optional(),
  mandateReference: optionalTrimmedString(64),
  accountNumber: optionalTrimmedString(34),
  reminderOffsets: reminderOffsetsSchema,
  remindersEnabled: z.coerce.boolean().optional(),
  notes: optionalTrimmedString(2000),
});
export type UpdateLoanInput = z.infer<typeof updateLoanSchema>;

export const loanListQuerySchema = paginationSchema.extend({
  vehicleId: uuidSchema.optional(),
  status: csvEnum(LOAN_STATUSES),
  lender: optionalTrimmedString(160),
  /** Only loans with at least one overdue installment. */
  overdueOnly: z.coerce.boolean().default(false),
  /** Only loans with an installment due within this many days. */
  dueWithinDays: z.coerce.number().int().min(0).max(365).optional(),
  search: optionalTrimmedString(160),
});
export type LoanListQuery = z.infer<typeof loanListQuerySchema>;

export const installmentListQuerySchema = paginationSchema
  .extend({
    status: csvEnum(INSTALLMENT_STATUSES),
    loanId: uuidSchema.optional(),
    vehicleId: uuidSchema.optional(),
  })
  .and(dateRangeSchema);
export type InstallmentListQuery = z.infer<typeof installmentListQuerySchema>;

export const upcomingEmiQuerySchema = z.object({
  /** Horizon in days. Defaults to a month, which is one EMI cycle. */
  days: z.coerce.number().int().min(1).max(365).default(30),
  vehicleId: uuidSchema.optional(),
  includeOverdue: z.coerce.boolean().default(true),
});
export type UpcomingEmiQuery = z.infer<typeof upcomingEmiQuerySchema>;

export const recordLoanPaymentSchema = z
  .object({
    installmentId: uuidSchema.optional(),
    amount: amountSchema('amount paid'),
    paidAt: z.coerce.date().optional(),
    method: loanPaymentMethodSchema.default('BANK_TRANSFER'),
    kind: loanPaymentKindSchema.default('INSTALLMENT'),
    reference: optionalTrimmedString(120),
    /** Late fee or bounce charge collected alongside the installment. */
    penalty: optionalAmountSchema,
    notes: optionalTrimmedString(1000),
  })
  .refine((value) => value.kind !== 'INSTALLMENT' || value.installmentId !== undefined, {
    message: 'Select the installment this payment settles.',
    path: ['installmentId'],
  });
export type RecordLoanPaymentInput = z.infer<typeof recordLoanPaymentSchema>;

export const waiveInstallmentSchema = z.object({
  reason: trimmedString(4, 500),
});
export type WaiveInstallmentInput = z.infer<typeof waiveInstallmentSchema>;

export const closeLoanSchema = z.object({
  status: z.enum(['CLOSED', 'FORECLOSED', 'CANCELLED', 'DEFAULTED']),
  closedAt: z.coerce.date().optional(),
  /** Amount settled to close the facility early. */
  settlementAmount: optionalAmountSchema,
  reference: optionalTrimmedString(120),
  notes: optionalTrimmedString(1000),
});
export type CloseLoanInput = z.infer<typeof closeLoanSchema>;

/**
 * Provider sync request.
 *
 * A loan number on its own is never enough: retrieval needs a supported
 * provider, an authorised consent reference and an account the caller can
 * prove they hold. The schema makes that explicit rather than implying that
 * any loan number can be looked up.
 */
export const syncLoanSchema = z.object({
  provider: optionalTrimmedString(60),
  consentReference: optionalTrimmedString(120),
  /** Apply provider figures instead of only reporting the differences. */
  apply: z.coerce.boolean().default(false),
});
export type SyncLoanInput = z.infer<typeof syncLoanSchema>;

/** Preview an amortisation schedule before committing to a loan record. */
export const previewScheduleSchema = z.object({
  principal: amountSchema('loan amount'),
  annualRatePercent: z.coerce.number().min(0).max(60),
  interestType: interestTypeSchema.default('REDUCING_BALANCE'),
  tenureMonths: z.coerce.number().int().min(1).max(360),
  frequency: emiFrequencySchema.default('MONTHLY'),
  firstDueDate: z.coerce.date(),
});
export type PreviewScheduleInput = z.infer<typeof previewScheduleSchema>;

export const importInstallmentsSchema = z.object({
  /** Where these rows came from — recorded on every imported installment. */
  source: z.enum(['IMPORT', 'PROVIDER_SYNC', 'DOCUMENT_EXTRACTION']).default('IMPORT'),
  providerName: optionalTrimmedString(60),
  replaceUnpaid: z.coerce.boolean().default(false),
  installments: z
    .array(
      z.object({
        number: z.coerce.number().int().min(1).max(600),
        dueDate: z.coerce.date(),
        principal: z.coerce.number().min(0).max(1_000_000_000),
        interest: z.coerce.number().min(0).max(1_000_000_000),
        totalDue: z.coerce.number().min(0).max(1_000_000_000),
        status: installmentStatusSchema.optional(),
        amountPaid: optionalAmountSchema,
        paidAt: z.coerce.date().optional(),
        paymentReference: optionalTrimmedString(120),
      }),
    )
    .min(1, 'Provide at least one installment.')
    .max(600),
});
export type ImportInstallmentsInput = z.infer<typeof importInstallmentsSchema>;
